### ISSUE TITLE
module Ecto.Type is not loaded and could not be found

### ISSUE THREAD

**Issue by enjolras1205** [onboardingsystems/enum_type#12]
compile error when ecto is not import: 
module Ecto.Type is not loaded and could not be found

mix new enum_type_test and modify enum_type_test.ex to below will reproduce the error:
defmodule EnumTypeTest do
  use EnumType

  defenum Color do
    value(Red, "red")
    value(Blue, "blue")
  end
end

mix compile
Compiling 1 file (.ex)

== Compilation error in file lib/enum_type_test.ex ==
** (CompileError) lib/enum_type_test.ex:4: module Ecto.Type is not loaded and could not be found
    (elixir 1.10.4) expanding macro: Kernel.use/1
    lib/enum_type_test.ex:4: EnumTypeTest.Color (module)

**Comment by rm-rf-etc** [comment]
I experienced this too. Then I happened to check the tags, seems that the docs don't mention the latest version number. Upgrading to `{:enum_type, "~> 1.1.2"}` fixed the issue for me.

**Comment by cadebward** [comment]
fixed via 272b57d9cb97df2f9dcfbc74d0ed70dafff789d0
