### ISSUE TITLE
defenum block lines show as unreachable when using code coverage tools.

### ISSUE THREAD

**Issue by scouten** [onboardingsystems/enum_type#2]
The entire body of the `defenum` block shows as not reached when using a code coverage tool, even if the enum is in use.

Please see:

* [Example project](https://github.com/scouten/enum_type_coverage_gap)
* [Coveralls report](https://coveralls.io/builds/22058277/source?filename=lib/coverage_gap.ex)

I'm aiming for very high coverage in a library that is using `enum_type` (which is otherwise *just* what I needed) and this is a non-trivial miss.

**Comment by brettv** [comment]
I suspect it is related to the fact that defenum is a macro.

I found this on excoveralls which seems related.

https://github.com/parroty/excoveralls/issues/59
