### ISSUE TITLE
Push latest release to hex

### ISSUE THREAD

**Issue by axelson** [onboardingsystems/enum_type#7]
Hi, thanks for this library! It looks like it does exactly what I am looking for right now 🎉 

Right now I only see 1.0.1 and 1.0.0 releases on hex.pm: https://hex.pm/packages/enum_type but the Readme lists 1.1.1 as the latest. I think the disconnect is that the latest releases haven't been pushed to hex. Can you push up the releases?

**Comment by brettv** [comment]
We don't have access to the hex.pm account that this was originally published under.  If we can transfer ownership of the account we will push an updated version.  In the mean time, I suggest pulling it directly from GitHub using something like this in your mix.exs:

```
{:enum_type, github: "onboardingsystems/enum_type", tag: "v1.1.2"}
```

**Comment by axelson** [comment]
Okay, thanks for the info!
